options:
  fsid:
    type: string
    description: |
      fsid of the ceph cluster. To generate a suitable value use `uuid`
      .
      This configuration element is mandatory and the service will fail on
      install if it is not provided.
  auth-supported:
    type: string
    default: cephx
    description: |
      Which authentication flavour to use.
      .
      Valid options are "cephx" and "none".  If "none" is specified,
      keys will still be created and deployed so that it can be
      enabled later.
  monitor-secret:
    type: string
    description: |
      This value will become the mon. key. To generate a suitable value use:
      .
        ceph-authtool /dev/stdout --name=mon. --gen-key
      .
      This configuration element is mandatory and the service will fail on
      install if it is not provided.
  monitor-count:
    type: int
    default: 3
    description: |
      How many nodes to wait for before trying to create the monitor cluster
      this number needs to be odd, and more than three is a waste except for
      very large clusters.
  osd-devices:
    type: string
    default: /dev/vdb
    description: |
      The devices to format and set up as osd volumes.
      .
      These devices are the range of devices that will be checked for and
      used across all service units.
  ephemeral-unmount:
    type: string
    description: |
      Cloud instances provider ephermeral storage which is normally mounted
      on /mnt.
      .
      Providing this option will force an unmount of the ephemeral device
      so that it can be used as a OSD storage device.  This is useful for
      testing purposes (cloud deployment is not a typical use case).
  source:
    type: string
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - cloud:folsom-proposed
        - http://my.archive.com/ubuntu main
      .
      The last option should be used in conjunction with the key configuration
      option.
      .
      Note that a minimum ceph version of 0.48.2 is required for use with this
      charm which is NOT provided by the packages in the main Ubuntu archive
      for precise.
  key:
    type: string
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
